### ISSUE TITLE
ORM fork for carrierwave backgrounder

### ISSUE THREAD

**Issue by essehabj** [neo4jrb/carrierwave-neo4j#13]
Grateful to community for extending carrierwave to Neo4j. 
I'm interested in re-creating the functionality of [ Carrierwave Backgrounder](https://github.com/lardawge/carrierwave_backgrounder) for Neo4j.

Goal: queue image re-sizing via Active Job / Sidekiq.

Target: Activemodel ORM from [Carrierwave Backgrounder](https://github.com/lardawge/carrierwave_backgrounder/blob/38b381faaace6c75f7310ea726dcd1be2604d3fb/lib/backgrounder/orm/activemodel.rb)

I'm unfortunately not far enough along in my rails career to fully comprehend the task ahead. I was hopeful the Neo4j community may be able to lend a hand and point me in the right direction.

As it stands -- if you attempt to use:
gemfile:
`gem 'carrierwave_backgrounder', :git => 'https://github.com/lardawge/carrierwave_backgrounder.git'`

model:
`property :attachment, type: String`
`mount_uploader :attachment, AttachmentUploader`
`process_in_background :attachment`

You'll get this error:
`undefined method process_in_background'`

[Stacktrace in this gist.](https://gist.github.com/essehabj/fdf65e67a2c08937659243bde3d55d37)

Unsure if @cheerfulstoic or @reu or others may have most familiarity on this one.

**Comment by cheerfulstoic** [comment]
Sorry, I don't use `carrierwave-neo4j` ;(

**Comment by cheerfulstoic** [comment]
Unfortunately not ;(   We haven't run into problems yet processing our paperclip images in the foreground (though in my current application of it we don't actually store thumbnails yet, so it's not really an issue at all).  I see there is a [delayed_paperclip](https://github.com/jrgifford/delayed_paperclip/) gem.  That just seems to be for `delayed_job` and `resque`.  We use `sidekiq` at my job, currently.

I imagine you could pretty easily create your own background job.  Perhaps you could save a temp file (either on a mounted volume in your datacenter if your web and background processes are on separate machines or even S3 for simple universal access).  You could then pass that path into a background job for any background tool, get the file, and attach it.

**Comment by essehabj** [comment]
Yes, this seems like the most appropriate route to go. Thanks for the guidance!
