### ISSUE TITLE
5/8 tests failing with neo4j 4.1.2

### ISSUE THREAD

**Issue by thermistor** [neo4jrb/carrierwave-neo4j#2]
Errors seem to be all related to the after_destroy callback that tries to set the uploader to nil.

The node however has frozen attributes and complains with: RuntimeError: can't modify frozen Hash

**Comment by dpisarewski** [comment]
Could you please provide more information, so I can reproduce the issue, e.g. gem versions for `carrierwave-neo4j` and `neo4j-core` and how you start the specs.

**Comment by thermistor** [comment]
I cloned this project, and ran `rspec`

The neo4j-core gem is:

neo4j-core (4.0.2)

Master is at 47a2fe2d6, the lib/carrierwave/neo4j/version.rb says 2.0.0.

**Comment by thermistor** [comment]
Hmm, now all tests fail with `RuntimeError: can't modify frozen Hash`
