### ISSUE TITLE
Error on uploading: Property values can only be of primitive types or arrays thereof

### ISSUE THREAD

**Issue by jelmerderonde** [neo4jrb/carrierwave-neo4j#3]
I'm using:
carrierwave (0.10.0)
carrierwave-neo4j (2.0.0)
and neo4j (4.1.2 db28af7)

And a very basic setup: https://gist.github.com/jelmerderonde/33494b0b679196bfbf90

However when I try to upload a file I immediately get the following error:

Neo4j::Server::CypherResponse::ResponseError at /users
Property values can only be of primitive types or arrays thereof

What can I do to resolve this issue?

**Comment by subvertallchris** [comment]
I'm not sure offhand but I'll see if I can check it out for you soon. I'm
out of town for the next few days. Sorry!

**Comment by dpisarewski** [comment]
I can't reproduce the error with the same gem versions. Which version of `neo4j-core` do you have?

I had only to fix the property declaration from your gist, and it worked fine.

```ruby
property :avatar_image, type: String
```

**Comment by jelmerderonde** [comment]
bundle show gives 4.0.3 for neo4j-core

**Comment by jelmerderonde** [comment]
@dpisarewski, sorry for the delay, I only now had time to look at it again. My gist was wrong, the actual code does include the 'type:'. I still have the same error, but will continue trying to fix it.

**Comment by dpisarewski** [comment]
Sorry, I could not reproduce this error. Can you post the backtrace?

**Comment by jelmerderonde** [comment]
@dpisarewski, I took a good long look at my Gemfile and messed around with the versions. I am unsure what the exact problem was, but it is working now.
