### ISSUE TITLE
version 2.0.1 release?

### ISSUE THREAD

**Issue by StaymanHou** [neo4jrb/carrierwave-neo4j#9]
Hi there,
Would love to know whether there's a schedule for releasing version 2.0.1. We could benefit from the PR #4 in our project.
Thx

**Comment by subvertallchris** [comment]
Just took care of it for you. https://rubygems.org/gems/carrierwave-neo4j/versions/2.0.1


Didn't realize that hadn't been done! Thanks for bringing it up.

**Comment by StaymanHou** [comment]
Awesome.
Thank you very much.
